[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "martsor"
version = "0.2.0"
description = "Python library for building Soroush Plus bots."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}

authors = [
    {name = "HidMart"}
]

keywords = [
    "soroush",
    "soroushplus",
    "splus",
    "bot",
    "telegram-like",
    "python"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

dependencies = []


[project.urls]
Homepage = "https://github.com/HidMart/martsor"
Repository = "https://github.com/HidMart/martsor"


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
include = ["martsor*"]