[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "martsor"
version = "0.1.0"
description = "Python library for building Soroush Plus bots."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"

authors = [
    { name = "HidMart" }
]

keywords = [
    "soroush",
    "soroush-plus",
    "splus",
    "bot",
    "telegram-bot",
    "python"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/HidMart/martsor"
Repository = "https://github.com/HidMart/martsor"
Issues = "https://github.com/HidMart/martsor/issues"

[tool.hatch.build.targets.wheel]
packages = ["martsor"]